### ISSUE TITLE
dMRIPrep roadmap

### ISSUE THREAD

**Issue by esavary** [nipreps/dmriprep#196]
- [ ] Integration of eddymotion into dMRIPrep
- [ ] Minimization of derivatives (cf. fMRIPrep action item)
- [ ] Integration of new telemetry system
- [ ] Implementation of new dMRI-specific “reportlets” into NiReports
- [ ] Pydra integration
